WebApplicationFinal.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using WebApplicationFinal.BLL.Interfaces;
using WebApplicationFinal.DAL.Models;
using WebApplicationFinal.PL.Helpers;
using WebApplicationFinal.PL.ViewModels;

namespace WebApplicationFinal.PL.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;
        //private readonly IEmployeeRepository _employeeRepo;
        //private readonly IDepartmentRepository _departmentRepo;

        public EmployeeController(IMapper mapper,IUnitOfWork unitOfWork/* IEmployeeRepository employeeRepo, IDepartmentRepository departmentRepo*/)
        {
            _mapper = mapper;
            _unitOfWork = unitOfWork;
            //_employeeRepo = employeeRepo;
            //_departmentRepo = departmentRepo; /*inject it in view for better performance because index doesnt use it*/

        }
        public IActionResult Index(string searchInp)
        {
            #region Comment
            //TempData.Keep();
            //ViewData["Message"] = "Hello ViewData";
            //ViewBag.Message = "Hello ViewBag"; 
            #endregion
            var employees = Enumerable.Empty<Employee>();
            if (String.IsNullOrEmpty(searchInp))
             employees = _unitOfWork.EmployeeRepository.GetAll();
            else
                employees= _unitOfWork.EmployeeRepository.SearchByName(searchInp.ToLower());
            var mappedEmps = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employees);

            return View(mappedEmps);
        }
        [HttpGet] //to go to empty form
        public IActionResult Create()
        {
            //ViewData["Departments"] = _departmentRepo.GetAll();

            //ViewBag.Departments = _departmentRepo.GetAll();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EmployeeViewModel employeeVM)
        {

            if (ModelState.IsValid) //server side validation for model validations
            {
                employeeVM.ImageName = DocumentSettings.UploadFile(employeeVM.Image, "images");

                var mappedEmp =_mapper.Map<EmployeeViewModel,Employee>(employeeVM);
                 _unitOfWork.EmployeeRepository.Add(mappedEmp);
                var count = _unitOfWork.Complete();
                if (count > 0)
                {
                    TempData["Message"] = "Department is Created Successfully";
                    
                }
                else
                {
                    TempData["Message"] = "An Error Has Ocurred, Department Not Created :(";

                }
                return RedirectToAction(nameof(Index));
            }
            return View(employeeVM);
        }
        [HttpGet]
        public IActionResult Details(int? id, string viewName = "Details")
        {
            if (!id.HasValue) // nullable has two properties hasvalue and value
                return BadRequest();
            var employee = _unitOfWork.EmployeeRepository.Get(id.Value); // should use id.value as it accepts parameter in int form
            if (employee is null)
                return NotFound();
            var mappedEmp = _mapper.Map<Employee, EmployeeViewModel>(employee);

          
            return View(viewName, mappedEmp);
        }
        // httpget by default
        public IActionResult Edit(int? id)
        {
            //ViewData["Departments"]=_departmentRepo.GetAll();
            //ViewBag.Departments = _departmentRepo.GetAll();
            return Details(id, "Edit");
        }
        [HttpPost]
        [ValidateAntiForgeryToken] //to refuse any edit on say id as example from resources otherthan website
        public IActionResult Edit([FromRoute]/*to make it take id only from url to avoid any other way to change it*/int id, EmployeeViewModel employeeVM)
        {
            if (id != employeeVM.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                //try and catch because it may throw exception if this Employee is in relation in database and it is immutable

                try
                {
                    employeeVM.ImageName = DocumentSettings.UploadFile(employeeVM.Image, "images");

                    var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);

                    _unitOfWork.EmployeeRepository.Update(mappedEmp);
                    _unitOfWork.Complete();  
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    //Log Exception
                    //Friendly Message
                    ModelState.AddModelError(string.Empty, ex.Message);

                }
            }
            return View(employeeVM);
        }
        public IActionResult Delete(int? id)
        {
            return Details(id, "Delete");
        }
        [HttpPost]
        [ValidateAntiForgeryToken] //to refuse any edit on say id as example from resources otherthan website
        public IActionResult Delete([FromRoute]/*to make it take id only from url to avoid any other way to change it*/int id, EmployeeViewModel employeeVM)
        {
            if (id != employeeVM.Id)
                return BadRequest();

            //try and catch because it may throw exception if this Employee is inrelation in database and it is immutable
            try
            {
                var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
                _unitOfWork.EmployeeRepository.Delete(mappedEmp);
               var count= _unitOfWork.Complete();
                if(count > 0)
                    DocumentSettings.DeleteFile(employeeVM.ImageName, "images");

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                //Log Exception
                //Friendly Message
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(employeeVM);

            }

        }

    }
}

WebApplicationFinal.PL/Controllers/RoleController.cs
using AutoMapper;
using DEMO.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplicationFinal.DAL.Models;
using WebApplicationFinal.PL.ViewModels;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace WebApplicationFinal.PL.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, IMapper mapper,UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _mapper = mapper;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                var roles = await _roleManager.Roles.Select(R => new RoleViewModel()
                {
                    Id = R.Id,
                    RoleName = R.Name
                }).ToListAsync();
                return View(roles);
            }
            else
            {
                var role = await _roleManager.FindByNameAsync(name);
                if(role is not null)
                {
                    var mappedRole = new RoleViewModel()
                    {
                        Id = role.Id,
                        RoleName = role.Name

                    };
                    return View(new List<RoleViewModel>() { mappedRole });
                }return View (Enumerable.Empty<RoleViewModel>());
              
            }
        }
        public async Task<IActionResult> Details(string id, string viewName = "Details")
        {
            if (id is null) // nullable has two properties hasvalue and value
                return BadRequest();
            var role = await _roleManager.FindByIdAsync(id);
            if (role is null)
                return NotFound();
            var mappedRole = _mapper.Map<IdentityRole, RoleViewModel>(role);


            return View(viewName, mappedRole);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel roleVM)
        {
            if (ModelState.IsValid)
            {
                var mappedRole=_mapper.Map<RoleViewModel,IdentityRole>(roleVM);
                await _roleManager.CreateAsync(mappedRole);
                return RedirectToAction(nameof(Index));
            }
            return View(roleVM);
        }
        public async Task<IActionResult> Edit(string id)
        {

            return await Details(id, "Edit");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, RoleViewModel updatedRole)
        {
            if (id != updatedRole.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var role = await _roleManager.FindByIdAsync(id);
                    role.Name = updatedRole.RoleName;
                    await _roleManager.UpdateAsync(role);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    //Log Exception
                    //Friendly Message
                    ModelState.AddModelError(string.Empty, ex.Message);

                }
            }
            return View(updatedRole);
        }
        public async Task<IActionResult> Delete(String id)
        {
            return await Details(id, "Delete");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDelete(string id)
        {


            //try and catch because it may throw exception if this Employee is inrelation in database and it is immutable
            try
            {

                var user = await _roleManager.FindByIdAsync(id);
                await _roleManager.DeleteAsync(user);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                //Log Exception
                //Friendly Message
                ModelState.AddModelError(string.Empty, ex.Message);
                return RedirectToAction("Error", "Home");
            }

        }
        public async Task<IActionResult> AddOrRemoveUsers(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null)
                return BadRequest();
            ViewBag.RoleId = roleId;
            var usersInRole = new List<UsersInRoleViewModel>();
            foreach (var user in await _userManager.Users.ToListAsync())
            {
                var userInRole = new UsersInRoleViewModel
                {
                    UserName = user.UserName,
                    UserId = user.Id
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                    userInRole.IsSelected = true;
                else
                    userInRole.IsSelected = false;
                usersInRole.Add(userInRole);
            }
            return View(usersInRole);
        }
        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(List<UsersInRoleViewModel> users, string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null)
                return BadRequest();
            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    var appUser = await _userManager.FindByIdAsync(user.UserId);
                    if (appUser != null)
                    {
                        if (user.IsSelected && !(await _userManager.IsInRoleAsync(appUser, role.Name)))
                            await _userManager.AddToRoleAsync(appUser, role.Name);
                        else if (!user.IsSelected && (await _userManager.IsInRoleAsync(appUser, role.Name)))
                            await _userManager.RemoveFromRoleAsync(appUser, role.Name);

                    }
                }
                return RedirectToAction(nameof(Edit), new { id = roleId });
            }
            return View(users);
        }
    } 
}

WebApplicationFinal.PL/Controllers/UserController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplicationFinal.DAL.Models;
using WebApplicationFinal.PL.Helpers;
using WebApplicationFinal.PL.ViewModels;

namespace WebApplicationFinal.PL.Controllers
{
	public class UserController: Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IMapper _mapper;

        public UserController(UserManager<ApplicationUser> userManager,SignInManager<ApplicationUser> signInManager ,IMapper mapper) 
		{
			_userManager = userManager;
			_signInManager = signInManager;
			_mapper = mapper;
        }

		public async  Task<IActionResult> Index(string email)
		{
			if (string.IsNullOrEmpty(email))
			{
				var users =await _userManager.Users.Select(U => new UserViewModel()
				{
					Id = U.Id,
					FName = U.FName,
					LName = U.LName,
					Email = U.Email,
					PhoneNumber = U.PhoneNumber,
					Roles = _userManager.GetRolesAsync(U).Result
				}).ToListAsync();
					return View(users);
			}
			else
			{
				var user=await _userManager.FindByEmailAsync(email);
				var mappedUser =  new UserViewModel()
				{
					Id = user.Id,
					FName = user.FName,
					LName = user.LName,
					Email = user.Email,
					PhoneNumber = user.PhoneNumber,
					Roles = _userManager.GetRolesAsync(user).Result
				};
				return View(new List<UserViewModel>() { mappedUser });
			}
		}
        public async Task<IActionResult> Details(string id, string viewName = "Details")
        {
            if (id is null) // nullable has two properties hasvalue and value
                return BadRequest();
            var user = await _userManager.FindByIdAsync(id);
            if (user is null)
                return NotFound();
            var mappedUser = _mapper.Map<ApplicationUser, UserViewModel>(user);


            return View(viewName, mappedUser);
        }
        public async Task<IActionResult> Edit(string id)
        {
            
            return await Details(id, "Edit");
        }
        [HttpPost]
        [ValidateAntiForgeryToken] 
        public async Task<IActionResult> Edit([FromRoute]string id, UserViewModel updateduser)
        {
            if (id != updateduser.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.FindByIdAsync(id);
                    user.FName = updateduser.FName;
                    user.LName = updateduser.LName;
                    user.PhoneNumber = updateduser.PhoneNumber;
                    //user.Email = updateduser.Email;
                    //user.SecurityStamp=Guid.NewGuid().ToString();
                    await _userManager.UpdateAsync(user);
                        return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    //Log Exception
                    //Friendly Message
                    ModelState.AddModelError(string.Empty, ex.Message);

                }
            }
            return View(updateduser);
        }
        public async Task<IActionResult> Delete(String id)
        {
            return await  Details(id, "Delete");
        }
        [HttpPost]
        [ValidateAntiForgeryToken] 
        public async Task<IActionResult> ConfirmDelete(string id)
        {
           

            //try and catch because it may throw exception if this Employee is inrelation in database and it is immutable
            try
            {

                var user = await _userManager.FindByIdAsync(id);
                await _userManager.DeleteAsync(user);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                //Log Exception
                //Friendly Message
                ModelState.AddModelError(string.Empty, ex.Message);
                return RedirectToAction("Error", "Home");
            }

        }
    }
}

WebApplicationFinal.PL/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Creative @ViewData["Title"]  Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/authLayout.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative @ViewData["Title"] Form</h1>
		 @RenderBody()
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	@await RenderSectionAsync("ValidationScriptSection", required: false) @* Make it at the same time of renderbody by await async*@
</body>
</html>

WebApplicationFinal.PL/Views/Shared/_ButtonsPartial.cshtml
@model string
<td>
    <a class="btn btn-warning"  asp-action="Details" asp-route-id="@Model">
        @* ican delete asp-controller because iam already in index action of Employee
        controler so by default he knows it is Employee controller*@
        <i class="fas fa-eye"></i> Details
    </a>
</td>
<td>
    <a class="btn btn-success"asp-action="Edit" asp-route-id="@Model">
        <i class="fas fa-edit"></i> Update
    </a>
</td>
<td>
    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model">
        <i class="fas fa-trash"></i> Delete
    </a>
</td>

WebApplicationFinal.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationFinal.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationFinal.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationFinal.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item ms-auto">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplicationFinal.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationScriptSection", required: false) @* Make it at the same time of renderbody by await async*@
</body>
</html>